// src/lib/cityStateData.js
// Comprehensive Indian Cities & States Database for 0ms Instant Autofill & Suggestions

const INDIAN_CITIES_DATABASE = [
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Delhi", state: "Delhi" },
  { city: "Bangalore", state: "Karnataka" },
  { city: "Bengaluru", state: "Karnataka" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Surat", state: "Gujarat" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Pimpri-Chinchwad", state: "Maharashtra" },
  { city: "Patna", state: "Bihar" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Ludhiana", state: "Punjab" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Kalyan-Dombivli", state: "Maharashtra" },
  { city: "Vasai-Virar", state: "Maharashtra" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Srinagar", state: "Jammu and Kashmir" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Navi Mumbai", state: "Maharashtra" },
  { city: "Allahabad", state: "Uttar Pradesh" },
  { city: "Prayagraj", state: "Uttar Pradesh" },
  { city: "Howrah", state: "West Bengal" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Guwahati", state: "Assam" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Hubli-Dharwad", state: "Karnataka" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Mysore", state: "Karnataka" },
  { city: "Mysuru", state: "Karnataka" },
  { city: "Gurgaon", state: "Haryana" },
  { city: "Gurugram", state: "Haryana" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Mira-Bhayandar", state: "Maharashtra" },
  { city: "Warangal", state: "Telangana" },
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Bhiwandi", state: "Maharashtra" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Kochi", state: "Kerala" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Gulbarga", state: "Karnataka" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Ujjain", state: "Madhya Pradesh" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Ulhasnagar", state: "Maharashtra" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "Jammu", state: "Jammu and Kashmir" },
  { city: "Sangli", state: "Maharashtra" },
  { city: "Belgaum", state: "Karnataka" },
  { city: "Belagavi", state: "Karnataka" },
  { city: "Mangalore", state: "Karnataka" },
  { city: "Mangaluru", state: "Karnataka" },
  { city: "Tirunelveli", state: "Tamil Nadu" },
  { city: "Malegaon", state: "Maharashtra" },
  { city: "Gaya", state: "Bihar" },
  { city: "Jalgaon", state: "Maharashtra" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Akola", state: "Maharashtra" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Rajahmundry", state: "Andhra Pradesh" },
  { city: "Bokaro", state: "Jharkhand" },
  { city: "Bellary", state: "Karnataka" },
  { city: "Patiala", state: "Punjab" },
  { city: "Agartala", state: "Tripura" },
  { city: "Bhagalpur", state: "Bihar" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Latur", state: "Maharashtra" },
  { city: "Dhule", state: "Maharashtra" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Korba", state: "Chhattisgarh" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Berhampur", state: "Odisha" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Ahmednagar", state: "Maharashtra" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Kollam", state: "Kerala" },
  { city: "Avadi", state: "Tamil Nadu" },
  { city: "Kadapa", state: "Andhra Pradesh" },
  { city: "Anantapur", state: "Andhra Pradesh" },
  { city: "Bilaspur", state: "Chhattisgarh" },
  { city: "Sambalpur", state: "Odisha" },
  { city: "Satara", state: "Maharashtra" },
  { city: "Ratlam", state: "Madhya Pradesh" },
  { city: "Eluru", state: "Andhra Pradesh" },
  { city: "Shimoga", state: "Karnataka" },
  { city: "Shivamogga", state: "Karnataka" },
  { city: "Chandrapur", state: "Maharashtra" },
  { city: "Junagadh", state: "Gujarat" },
  { city: "Thrissur", state: "Kerala" },
  { city: "Alwar", state: "Rajasthan" },
  { city: "Kakinada", state: "Andhra Pradesh" },
  { city: "Nizamabad", state: "Telangana" },
  { city: "Parbhani", state: "Maharashtra" },
  { city: "Tumkur", state: "Karnataka" },
  { city: "Tumakuru", state: "Karnataka" },
  { city: "Khammam", state: "Telangana" },
  { city: "Bihar Sharif", state: "Bihar" },
  { city: "Panipat", state: "Haryana" },
  { city: "Darbhanga", state: "Bihar" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Dewas", state: "Madhya Pradesh" },
  { city: "Ichalkaranji", state: "Maharashtra" },
  { city: "Karnal", state: "Haryana" },
  { city: "Bathinda", state: "Punjab" },
  { city: "Jalna", state: "Maharashtra" },
  { city: "Barasat", state: "West Bengal" },
  { city: "Purnia", state: "Bihar" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Farrukhabad", state: "Uttar Pradesh" },
  { city: "Sagar", state: "Madhya Pradesh" },
  { city: "Rourkela", state: "Odisha" },
  { city: "Durg", state: "Chhattisgarh" },
  { city: "Imphal", state: "Manipur" },
  { city: "Arrah", state: "Bihar" },
  { city: "Karimnagar", state: "Telangana" },
  { city: "Etawah", state: "Uttar Pradesh" },
  { city: "Ambernath", state: "Maharashtra" },
  { city: "Bharatpur", state: "Rajasthan" },
  { city: "Begusarai", state: "Bihar" },
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Tirupur", state: "Tamil Nadu" },
  { city: "Puducherry", state: "Puducherry" }
];

export const searchCities = (query = "") => {
  if (!query || String(query).trim().length < 2) return [];
  const cleanQ = String(query).trim().toLowerCase();
  
  return INDIAN_CITIES_DATABASE.filter(item => 
    item.city.toLowerCase().startsWith(cleanQ) || item.city.toLowerCase().includes(cleanQ)
  ).slice(0, 10);
};

export const getStateForCity = (cityName = "") => {
  if (!cityName) return "";
  const cleanCity = String(cityName).trim().toLowerCase();
  const match = INDIAN_CITIES_DATABASE.find(item => item.city.toLowerCase() === cleanCity);
  return match ? match.state : "";
};
